apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: staging-yam-realtoken
  name: staging-yam-realtoken
spec:
  selector:
    matchLabels:
      app: staging-yam-realtoken
  template:
    metadata:
      labels:
        app: staging-yam-realtoken
    spec:
      containers:
      - image: registry.digitalocean.com/yam-realtoken-cr/staging:b3a473c
        imagePullPolicy: IfNotPresent
        name: staging-yam-realtoken
        ports:
        - containerPort: 3000
          protocol: TCP